### ISSUE TITLE
Querying non-existing post results in error

### ISSUE THREAD

**Issue by marktani** [graphql-boilerplates/typescript-graphql-server#159]
## Reproduction

```
graphql create ts -b typescript-advanced
cd ts
yarn dev
```

Send this query:

```graphql
query c {
  post(id: "doesnotexist") {
    title
  }
}
```

Results in this error:

```json
{
  "data": null,
  "errors": [
    {
      "message": "Cannot return null for non-nullable field Query.post.",
      "locations": [
        {
          "line": 14,
          "column": 3
        }
      ],
      "path": [
        "post"
      ]
    }
  ]
}
```

## Improvement

I suggest a change for the `post` query definition in `src/schema.graphql`. It should return a non-required `Post` instead:

```diff
type Query {
  # ...
- post(id: ID!): Post!
+ post(id: ID!): Post
  # ...
}
```

From what I can see, this affects all but `minimal` boilerplates, so also `node-*` and the fullstack ones.

**Comment by manjula91** [comment]
@marktan Cool will do this for React Boilerplate & Node .

Just a question: This is to be done for advanced as well ?

**Comment by marktani** [comment]
Hey @manjula91, that's awesome 👌 

This needs to be done for all boilerplates that define the `post(id: ID!): Post!` query. To my knowledge, these are the ones:

* `node-basic`, `node-advanced`
* `typescript-basic`, `typescript-advanced`
* the `basic` and `advanced` fullstack boilerplates (React, RN, Vue)

**Comment by juicycleff** [comment]
Hi @marktani that's fine will get on with it

**Comment by manjula91** [comment]
@juicycleff you can take up vue. (RN,R, Node I am picking up)

**Comment by marktani** [comment]
Thanks for your help with this! :pray:
