### ISSUE TITLE
Database type choice

### ISSUE THREAD

**Issue by pvm** [graphql-boilerplates/typescript-graphql-server#221]
When we use the boilerplate (I think is all of it), he do not ask about what database I want to use, he creates mysql as default. I want to use postgres instead.

Can you update the cli to change that option?

**Comment by nikolasburk** [comment]
When using `graphql create`, the boilerplates are deployed to a Prisma Sandbox by default :slightly_smiling_face: 

To deploy to your own Prisma server with your own DB, run `prisma deploy --new`. The CLI will then ask you how to deploy  the Prisma API and that’s when you can setup your own Prisma server with a connected Postgres DB.

We will put that info into the READMEs soon!
