### ISSUE TITLE
advanced project cannot find module 'graphql-yoga'

### ISSUE THREAD

**Issue by nampdn** [graphql-boilerplates/typescript-graphql-server#232]
I just install a new project of an advanced template. After the installation, I cd to the project folder and do `yarn dev`. Everything is up except that it throws error like this:

>TSError: ⨯ Unable to compile TypeScript
src/index.ts (1,31): Cannot find module 'graphql-yoga'. (2307)
    at getOutput (/Users/projects/graph/node_modules/ts-node/src/index.ts:329:15)

I did rimraf node_modules and reinstall dependencies again by `yarn` and `npm install`, but neither works. I checked that `graphql-yoga` already specified in dependencies.

**Comment by gbouteiller** [comment]
@nampdn, this is a **graphql-yoga** error. It is discussed in [#297](https://github.com/graphcool/graphql-yoga/issues/297).
For now you can just downgrade your `graphql-yoga` version to `1.12.1`.

**Comment by marktani** [comment]
Thanks for bringing this up, @nampdn, and thanks for the workaround @gbouteiller.

This was now fixed in `graphql-yoga@1.13.1`, and the boilerplates have been upgrade to use this version.
