### ISSUE TITLE
TSError: ⨯ Unable to compile TypeScript

### ISSUE THREAD

**Issue by AlexanderChen1989** [graphql-boilerplates/typescript-graphql-server#254]
created application based on base or advanced template cant compile
![image](https://user-images.githubusercontent.com/2957936/40416075-faa8f092-5eae-11e8-8bb0-6cef799af9f6.png)

**Comment by marktani** [comment]
I cannot reproduce this issue. Here's what I did:

```
npm install -g graphql-cli prisma
graphql create ts-test # choose typescript-basic
cd ts-test
yarn dev
```

All works as expected.

What is your `ts-node` version? Here's mine

```console
$ ./node_modules/.bin/ts-node -v
ts-node v6.0.3
node v10.0.0
typescript v2.8.3
cache "/tmp/ts-node-3a695d60cbb9b0b59d8ad4566b629d170fdf844a99348363110aaae6934749a9/bb44c357ef614d597259161690a2488de1241f2c8934d92d9c51eda038ea469d"
```

**Comment by AlexanderChen1989** [comment]
fixed

**Comment by marktani** [comment]
How did you fix that, @AlexanderChen1989?

**Comment by AlexanderChen1989** [comment]
no, new commits fixed this problem,

**Comment by ruohki** [comment]
running into the same error as of today 
`
$ ts-node -v
ts-node v6.0.4
node v10.1.0
typescript v2.8.3
`

**Comment by ruohki** [comment]
after digging deeper into this i solved the issue by deleting the generated/ folder and regenerating it using prisma deploy
