### ISSUE TITLE
Generator prisma-binding is not installed. 

### ISSUE THREAD

**Issue by marktani** [graphql-boilerplates/typescript-graphql-server#289]
When I run `graphql create --boilerplate typescript-advance`, I get a lot of output, including this error:

```
post-deploy:
project database - Schema file was updated: src/generated/prisma.graphql

Running graphql get-schema --project database ✔
Generator prisma-binding is not installed. Please install prisma-binding version > 2.x to use "graphql codegen"

Running graphql codegen 
```

This looks like something needs to be adjusted in https://github.com/graphql-boilerplates/graphql-boilerplate-install.

**Comment by marktani** [comment]
I think the problem occurs due to this error that happens before:

```
node:48077) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security
 and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
error upath@1.0.2: The engine "node" is incompatible with this module. Expected version ">=4 <=9".
error Found incompatible module
```

**Comment by marktani** [comment]
my node version `v10.4.0`

**Comment by divyenduz** [comment]
I couldn't reproduce the problem. I have node `v.10.4.0`. [`prisma-binding`](https://github.com/graphql-boilerplates/typescript-graphql-server/blob/master/advanced/package.json#L14) is a dependency.

**Comment by marktani** [comment]
This is now fixed. It was an issue with an outdated `yarn.lock` file.
