### ISSUE TITLE
Documentation for "Static type generation"

### ISSUE THREAD

**Issue by Slessi** [graphql-boilerplates/typescript-graphql-server#304]
In the [Advanced README](https://github.com/graphql-boilerplates/typescript-graphql-server/blob/master/advanced/README.md), the following is mentioned:

> **Static type generation**: TypeScript types for GraphQL queries & mutations are generated in a build step

But I can't seem to find any indication on how to generate these types, is there some documentation somewhere that I am not seeing?

**Comment by dbuezas** [comment]
Had the same problem but for the Basic README (only prisma-bindings). Here's how i got it solved:
https://www.prisma.io/docs/reference/prisma-bindings/code-generation-cosha9rah3

So call `prisma-binding  --language typescript  --outputBinding src/generated/prisma.ts`
or better configure in `graphqlconfig.yml` as in the link and hook to the post-deploy hook in `prisma.yml`
