### ISSUE TITLE
Endpoint not updated in .graphqlconfig.yml after initial deploy

### ISSUE THREAD

**Issue by kbrandwijk** [graphql-boilerplates/typescript-graphql-server#67]

**Comment by marktani** [comment]
`.graphqlconfig.yml` doesn't contain any endpoint information about the deployed service. Can you elaborate?

**Comment by kbrandwijk** [comment]
Sorry, that was my mistake. I got an error on the graphql-cli about localhost:4000, and I connected the wrong dots. The install script is fine.
