### ISSUE TITLE
Unclear instructions 

### ISSUE THREAD

**Issue by mkozhukharenko** [graphql-boilerplates/typescript-graphql-server#7]
I have troubles with graphql-boilerplate:

1. `graphql create my-app`
select ‘advanced typescript’
2. `cd my-app`

3. `graphcool deploy` -> 
select ‘local’ and got ERROR: `Cannot read property 'getDeployEndpoint' of undefined`

deploying to shared-cluster works

Expected behaviour:
It should work or clear error should be printed

4. `yarn deploy` and got ERROR: `--dotenv flag is set but .env.prod file is missing`

Expected behaviour: there should be an instruciton about .env.prod file

**Comment by marktani** [comment]
3. are you still running into this problem? If so, please run `touch ~/.graphcool/cache.yml` and try again.

**Comment by mkozhukharenko** [comment]
now it works since it deploys to shared cluster (this option it taken from cache, I guess)

**Comment by marktani** [comment]
I iterated the instructions a lot, let me know if you have any other specific questions in a new issue.
