### ISSUE TITLE
Boilerplate does no longer install

### ISSUE THREAD

**Issue by kbrandwijk** [graphql-boilerplates/typescript-graphql-server#77]
install.js reappeared in the root, causing the setup to fail.

**Comment by johannpinson** [comment]
There is also some merges "failed" =>
https://github.com/graphql-boilerplates/typescript-graphql-server/blob/44246ff2b2d1f95ee09e2b6483c7da334adb223e/basic/src/index.ts#L2

**Comment by nikolasburk** [comment]
I'm currently fixing that, expect an update within the next hour 👍

**Comment by michaelchiche** [comment]
there is also an issue with the advanced template since it looks like the graphcool.yml should be renamed prisma.yml @nikolasburk

**Comment by nikolasburk** [comment]
Thanks a lot for all your input guys 🙏 I just pushed updated versions of the `basic` and `advanced` boilerplates. I tested both using `graphql create` and it worked. Would be awesome if you could give them a run as well to make sure everything works as expected 🙂   @michaelchiche @johannpinson
