### ISSUE TITLE
Unexpected token H in JSON at position 0

### ISSUE THREAD

**Issue by gHashTag** [graphql-boilerplates/typescript-graphql-server#8]
Following all instructions reached the point

https://github.com/graphql-boilerplates/typescript-graphql-server/tree/master/basic#common-questions  

Replace the Key at the bottom of the page with your secret from the graphcool.yml
https://github.com/graphql-boilerplates/typescript-graphql-server/blob/b0b82f8b62d0fba81bd23852d775ff813dd28815/basic/graphcool.yml#L5

Got a token on it here
![2017-12-25 22 26 55](https://user-images.githubusercontent.com/6774813/34342503-24501ef4-e9c3-11e7-90b1-1d0da5262a10.png)

I put it in here.
![2017-12-25 22 27 36](https://user-images.githubusercontent.com/6774813/34342504-36ca6724-e9c3-11e7-8412-ad5a35dca482.png)

I get a response to the mutation

![2017-12-25 22 32 42](https://user-images.githubusercontent.com/6774813/34342516-8a7e1d8e-e9c3-11e7-96cc-4b680cfdfd49.png)

What's wrong?

**Comment by marktani** [comment]
You used the string `mytopsecret`, but the secret used is `mysecret123`.

**Comment by gHashTag** [comment]
This I showed the place where I change it. Tried it differently.

**Comment by marktani** [comment]
I don't understand your last message.

**Comment by gHashTag** [comment]
Sorry for my English. 
![2017-12-28 21 19 22](https://user-images.githubusercontent.com/6774813/34419427-e426c1ee-ec14-11e7-86e5-42caad21bea7.png)

Even if I do not, then everything also. I get a token and the same error.
Showed the place where I change my password

**Comment by marktani** [comment]
Could you prepare a Github repository and share a list of steps that I can follow to reproduce your issue? 🙂 I am not able to reproduce it at the moment.

**Comment by gHashTag** [comment]
# Github repository
https://github.com/gHashTag/test-typescript-graphql-server

### Step 1 Initialized project, created database, started localserver

![](https://github.com/gHashTag/test-typescript-graphql-server/blob/master/asset/step1.png?raw=true)

### Step 2 Created token

![](https://github.com/gHashTag/test-typescript-graphql-server/blob/master/asset/step2.png?raw=true)

### Step 3 Added token to playground app/default

![](https://github.com/gHashTag/test-typescript-graphql-server/blob/master/asset/step3.png?raw=true)

### Step 4 Added token to playground database/dev

![](https://github.com/gHashTag/test-typescript-graphql-server/blob/master/asset/step4.png?raw=true)

### Step 5 Mutation

![](https://github.com/gHashTag/test-typescript-graphql-server/blob/master/asset/step5.png?raw=true)

**Comment by marktani** [comment]
Thanks a lot! 🙂 

The token you are generating with `mysecret123` is only useful for the database schema (as you did in step 4), but step 3 is unnecessary and probably causes the error message. Please remove the `Authorization` header there.

**Comment by gHashTag** [comment]
### Remove the Authorization header.
![2017-12-28 22 55 34](https://user-images.githubusercontent.com/6774813/34421789-7a4b040c-ec22-11e7-8bfa-0638d8c6d26a.png)

```
Server is running on http://localhost:4000
Error: Unexpected token H in JSON at position 0
    at Object.checkResultAndHandleErrors (/Users/xyz/my-app/node_modules/graphql-tools/src/stitching/errors.ts:84:7)
    at Object.<anonymous> (/Users/xyz/my-app/node_modules/graphql-tools/src/stitching/delegateToSchema.ts:91:14)
    at step (/Users/xyz/my-app/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:40:23)
    at Object.next (/Users/xyz/my-app/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:21:53)
    at fulfilled (/Users/xyz/my-app/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:12:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
```

**Comment by schickling** [comment]
Can you re-run with `debug: true` when creating `new Graphcool()`?

**Comment by marktani** [comment]
I ran into the same problem, and this is the real error message:

> HTTP method not allowed, supported methods: GET

Full logs:

```
query:
Request to http://localhost:60000/permissions-demo/dev:
query:
mutation ($_data: UserCreateInput!) {
  createUser(data: $_data) {
    id
    createdAt
    role
    email
    password
  }
}
operationName: null
variables:
{
  "_data": {
    "role": "ADMIN",
    "email": "admin@admin.com",
    "password": "$2a$10$XCV1O/xvuacIjGlT24.5demCdd0AYhym2BGKHl76hVvTdOk3HmnS."
  }
}
{ SyntaxError: Unexpected token H in JSON at position 0
    at JSON.parse (<anonymous>)
    at /Users/marktani/projects/playground/permissions-demo/node_modules/apollo-link-http/lib/bundle.umd.js:46:25
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  response:
   Body {
     url: 'http://localhost:60000/permissions-demo/dev',
     status: 405,
     statusText: 'Method Not Allowed',
     headers: Headers { _headers: [Object] },
     ok: false,
     body:
      PassThrough {
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 4,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: true,
        _transformState: [Object] },
     bodyUsed: true,
     size: 0,
     timeout: 0,
     _raw: [ <Buffer 48 54 54 50 20 6d 65 74 68 6f 64 20 6e 6f 74 20 61 6c 6c 6f 77 65 64 2c 20 73 75 70 70 6f 72 74 65
64 20 6d 65 74 68 6f 64 73 3a 20 47 45 54> ],
     _abort: false,
     _bytes: 47 },
  statusCode: 405,
  bodyText: 'HTTP method not allowed, supported methods: GET' }
Error: Unexpected token H in JSON at position 0
    at Object.checkResultAndHandleErrors (/Users/marktani/projects/playground/permissions-demo/node_modules/graphql-tool
s/dist/stitching/errors.js:69:36)
    at Object.<anonymous> (/Users/marktani/projects/playground/permissions-demo/node_modules/graphql-tools/dist/stitchin
g/delegateToSchema.js:88:52)
    at step (/Users/marktani/projects/playground/permissions-demo/node_modules/graphql-tools/dist/stitching/delegateToSc
hema.js:40:23)
    at Object.next (/Users/marktani/projects/playground/permissions-demo/node_modules/graphql-tools/dist/stitching/deleg
ateToSchema.js:21:53)
    at fulfilled (/Users/marktani/projects/playground/permissions-demo/node_modules/graphql-tools/dist/stitching/delegat
eToSchema.js:12:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by marktani** [comment]
I can reproduce this when following https://github.com/nikolasburk/permissions-demo, which is using port `60000`. This is my `docker ps`:

```
CONTAINER ID        IMAGE                                   COMMAND                  CREATED             STATUS              PORTS                      NAMES
242b06bf52b1        graphcool/graphcool-dev:1.0.0-beta2.1   "/app/bin/single-s..."   19 hours ago        Up 19 hours         0.0.0.0:60001->60001/tcp   localdatabase_graphcool-database_1
fa9fd3a8b0c9        graphcool/graphcool-dev:0.11.0          "/app/bin/single-s..."   7 days ago          Up 19 hours         0.0.0.0:60000->60000/tcp   local_graphcool_1
913095c88222        mysql:5.7                               "docker-entrypoint..."   7 days ago          Up 19 hours         0.0.0.0:7777->3306/tcp     graphcool-db
6929cc6625c5        mysql:5.7                               "docker-entrypoint..."   8 days ago          Up 19 hours         3306/tcp                   local_graphcool-db_1
01b3a91fa30d        graphcool/localfaas:0.11.0              "/app/bin/localfaas"     8 days ago          Up 19 hours         0.0.0.0:60050->60050/tcp   local_localfaas_1
```

Note that _my_ port is `60001`, and `60000` is the framework docker image. I could fix my problem when updating the port in `.env` to `60001`.

@gHashTag, what's the output for your `docker ps`? 🙂

**Comment by gHashTag** [comment]
I'm completely confused 🙂
I'm running this project
https://github.com/nikolasburk/permissions-demo
or
https://github.com/graphql-boilerplates/typescript-graphql-server/tree/master/basic
this?

**Comment by marktani** [comment]
You can continue with https://github.com/graphql-boilerplates/typescript-graphql-server/tree/master/basic :)

I can now reliably reproduce the error as I described in my previous comment. 

Can you share the output of `docker ps`? 🙂

**Comment by gHashTag** [comment]
```
CONTAINER ID        IMAGE                                   COMMAND                  CREATED             STATUS              PORTS                      NAMES
358136cad0e4        graphcool/graphcool-dev:1.0.0-beta2.1   "/app/bin/single-s..."   26 hours ago        Up 5 hours          0.0.0.0:60001->60001/tcp   localdatabase_graphcool-database_1
d26141dc95fb        mysql:5.7                               "docker-entrypoint..."   26 hours ago        Up 5 hours          0.0.0.0:7777->3306/tcp     graphcool-db
3209616a05ac        graphcool/graphcool-dev:0.11.0          "/app/bin/single-s..."   10 days ago         Up 5 hours          0.0.0.0:60000->60000/tcp   local_graphcool_1
07d7ba91e20b        graphcool/localfaas:0.11.0              "/app/bin/localfaas"     10 days ago         Up 5 hours          0.0.0.0:60050->60050/tcp   local_localfaas_1
d1849f34422d        mysql:5.7                               "docker-entrypoint..."   10 days ago         Up 5 hours          3306/tcp                   local_graphcool-db_1
```

**Comment by marktani** [comment]
Yes, you have the same problem as me. You need to update every occurence of `localhost:60000` to `localhost:60001` 🙂 

I think for `typescript-basic`, [this line](https://github.com/graphql-boilerplates/typescript-graphql-server/blob/master/basic/src/index.ts#L38) is the only one you need to update.

It should say

```sh
  endpoint: 'http://localhost:60001/graphql-boilerplate/dev',
```

instead of 

```sh
  endpoint: 'http://localhost:60000/graphql-boilerplate/dev',
```

**Comment by gHashTag** [comment]
```graphql create my-app --boilerplate typescript-basic```

![2018-01-03 18 38 54](https://user-images.githubusercontent.com/6774813/34527107-8c7d9abc-f0b5-11e7-91f3-5828946e6d48.png)

> update every occurence of localhost:60000 to localhost:60001 [this line](https://github.com/graphql-boilerplates/typescript-graphql-server/blob/master/basic/src/index.ts#L38
)

```graphcool deploy```

![2018-01-03 18 44 00](https://user-images.githubusercontent.com/6774813/34527285-24bbe284-f0b6-11e7-8d2b-3805f749822d.png)

Is this just happening to me 🙂?

**Comment by marktani** [comment]
No, I've seen it before as well 🙂 
Looks like your local cluster is in an inconsistent state, could you try `graphcool local nuke` to **completely wipe the local state**, and then try deploying again?

**Comment by gHashTag** [comment]
After ```graphcool local nuke```

![2018-01-03 18 59 06](https://user-images.githubusercontent.com/6774813/34527906-33e9cc92-f0b8-11e7-9a6e-c35e1925cf1d.png)

Which cluster should I choose? 

```local``` or ```shared-public-demo```?

**Comment by marktani** [comment]
Please choose `local` 🙂

**Comment by gHashTag** [comment]
So it should be or should be somehow corrected?

` ▸    'ENOENT': ENOENT: no such file or directory, open '/Users/xyz/.graphcool/config.yml'`

![2018-01-03 19 03 46](https://user-images.githubusercontent.com/6774813/34528093-d8be6228-f0b8-11e7-8308-e7ac54c96d44.png)

**Comment by gHashTag** [comment]
`docker ps`
```
CONTAINER ID        IMAGE                                   COMMAND                  CREATED             STATUS              PORTS                      NAMES
1c30e191da46        graphcool/graphcool-dev:1.0.0-beta2.1   "/app/bin/single-s..."   3 minutes ago       Up 3 minutes        0.0.0.0:60000->60000/tcp   localdatabase_graphcool-database_1
bfe567d2fc1d        mysql:5.7                               "docker-entrypoint..."   8 minutes ago       Up 8 minutes        0.0.0.0:7777->3306/tcp     graphcool-db```

**Comment by marktani** [comment]
This will be fixed in the **beta3** release very soon 🙂 
I'll ping you here once we released it.

**Comment by gHashTag** [comment]
@marktani When are the news waiting for me?
🙂

**Comment by schickling** [comment]
@gHashTag you should be able to install the newest beta via `npm i -g graphcool@beta3`. We'll shortly announce it. 🎉

**Comment by gHashTag** [comment]
wound up 🎉
