### ISSUE TITLE
src/generated/prisma.ts not regenated

### ISSUE THREAD

**Issue by Fonz001** [graphql-boilerplates/typescript-graphql-server#96]
src/generated/prisma.ts is not regenerated at prisma deploy (for both the advanced and basic boilerplate). 

src/generated/prisma.graphql is regenerated however....

Thnx in advance!

**Comment by Fonz001** [comment]
Thnx to graphcool slack I found the solution: Install `graphql-cli` and run `graphql prepare` . Would be nice to have this command integrated in the package.json or the prisma deploy. :-)

**Comment by marktani** [comment]
Thanks for reporting, @Fonz001! This is fixed in the latest `prisma` version: https://github.com/graphcool/prisma/issues/1695.
