### ISSUE TITLE
Strict typing and middleware

### ISSUE THREAD

**Issue by blocka** [graphql-boilerplates/typescript-graphql-server#99]
The boilerplate is currently not using `strict: true` which takes away some of the experience of TS.
Besides that, I am finding it unclear how to properly type the resolvers:

```
    user(parent, { id }, context: Context, info) {
```
What are the types of parent, the second argument and info?

I've seen example middleware that looked like this:

```
server.express.post(server.options.endpoint, (req, res, next, db) => .....
````
How is that last parameter supposed to be typed?

**Comment by kbrandwijk** [comment]
I believe the full typing is `parent: any, args: { [key: string]: any }, context: Context, info: GraphQLResolveInfo | string | undefined`

**Comment by blocka** [comment]
Thanks.
How about the middleware?

**Comment by kbrandwijk** [comment]
@blocka I don't recognize that example middleware.

**Comment by blocka** [comment]
I saw it here: https://github.com/LawJolla/prisma-auth0-example/blob/master/server/src/middleware/getUser.js

**Comment by kbrandwijk** [comment]
See: https://github.com/LawJolla/prisma-auth0-example/blob/master/server/src/index.js#L95

In the example, `db` points to the instance of `Prisma`, so that's the type. That example however, has nothing to do with this boilerplate, as it is not used in it.
